# Generated by Django 3.0.5 on 2020-05-28 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nomenclature',
            old_name='alignment_id',
            new_name='alignment',
        ),
        migrations.RenameField(
            model_name='nomenclature',
            old_name='reference_proteinSequence_id',
            new_name='reference_proteinSequence',
        ),
        migrations.RenameField(
            model_name='nomenclaturepositions',
            old_name='nomenclature_id',
            new_name='nomenclature',
        ),
        migrations.RenameField(
            model_name='organism',
            old_name='taxon_id',
            new_name='taxon',
        ),
        migrations.RenameField(
            model_name='protein',
            old_name='organism_id',
            new_name='organism',
        ),
        migrations.RenameField(
            model_name='proteinsequence',
            old_name='alignment_id',
            new_name='alignment',
        ),
        migrations.RenameField(
            model_name='proteinsequence',
            old_name='protein_id',
            new_name='protein',
        ),
    ]
