# Generated by Django 3.0.5 on 2020-05-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0002_auto_20200528_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alignment',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='organism',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='mesh_id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='proteinsequence',
            name='accession',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='gb_taxon_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
