# Generated by Django 3.0.5 on 2020-05-29 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0003_auto_20200528_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protein',
            name='organism',
        ),
        migrations.AddField(
            model_name='proteinsequence',
            name='organism',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proteinsequence',
            name='taxon',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='explorer.Taxon'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxon',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.DeleteModel(
            name='Organism',
        ),
    ]
