# Generated by Django 3.0.5 on 2020-05-29 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0005_alignment_protein'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(max_length=50, unique=True)),
                ('organism', models.CharField(max_length=200)),
                ('collection_date', models.DateTimeField(null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('host', models.CharField(max_length=100, null=True)),
                ('isolation_source', models.CharField(max_length=100, null=True)),
                ('coded_by', models.CharField(max_length=50, null=True)),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.Protein')),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.Taxon')),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.TextField()),
                ('offset', models.IntegerField()),
                ('alignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.Alignment')),
                ('sequence_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.SequenceRecord')),
            ],
        ),
    ]
