# Generated by Django 3.0.5 on 2020-05-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0006_sequence_sequencerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencerecord',
            name='isolate',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
