# Generated by Django 3.0.5 on 2020-05-29 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0007_sequencerecord_isolate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomenclature',
            name='reference_proteinSequence',
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='reference_sequenceRecord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='explorer.SequenceRecord'),
        ),
        migrations.DeleteModel(
            name='ProteinSequence',
        ),
    ]
