# Generated by Django 3.0.5 on 2020-05-31 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0010_auto_20200530_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpitopeExperiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=75)),
                ('assay_type', models.CharField(max_length=50)),
                ('assay_result', models.CharField(max_length=50)),
                ('mhc_allele', models.CharField(max_length=30)),
                ('mhc_class', models.CharField(max_length=30)),
                ('exp_method', models.CharField(max_length=100)),
                ('measurement_type', models.CharField(max_length=100)),
                ('epitope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.Epitope')),
            ],
        ),
    ]
