# Generated by Django 3.0.5 on 2020-05-31 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0011_epitopeexperiment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomenclature',
            name='reference_sequenceRecord',
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='protein',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='explorer.Protein'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='reference',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='explorer.Sequence'),
            preserve_default=False,
        ),
    ]
