# Generated by Django 3.0.5 on 2020-05-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0013_remove_nomenclature_alignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclaturepositions',
            name='minor',
            field=models.CharField(max_length=5),
        ),
    ]
