# Generated by Django 3.0.5 on 2020-06-04 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0015_auto_20200531_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdb_id', models.CharField(max_length=10)),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.Taxon')),
            ],
        ),
        migrations.CreateModel(
            name='StructureChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1)),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.Protein')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.Structure')),
            ],
        ),
        migrations.AlterField(
            model_name='nomenclatureposition',
            name='minor',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='StructureChainSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.IntegerField()),
                ('sequence', models.TextField()),
                ('alignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.Alignment')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.StructureChain')),
            ],
        ),
        migrations.CreateModel(
            name='StructureChainAtom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resix', models.IntegerField()),
                ('resid', models.IntegerField()),
                ('resn', models.CharField(max_length=1)),
                ('atom', models.CharField(max_length=5)),
                ('element', models.CharField(max_length=5)),
                ('charge', models.IntegerField()),
                ('occupancy', models.FloatField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.StructureChain')),
            ],
        ),
    ]
