# Generated by Django 3.0.5 on 2020-06-05 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0016_auto_20200604_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structurechain',
            name='protein',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='explorer.Protein'),
        ),
    ]
