# Generated by Django 3.0.5 on 2020-06-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0018_auto_20200605_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='pdb_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
